### PR TITLE
Replace functions by state access in tower

### PR DESCRIPTION
**Pull request by JaafarRammal**
# Summary

Tower used base agent functions to access state. These functions could be overridden by custom agents accidentally.

### CODE REVIEW

**Review by udai-arneja — APPROVED** [review]
LGTM, nice

**Review by jzzheng22 — COMMENTED** [review]
We're still keeping the getter functions in agent though right? If so, then happy to approve.

**Comment by JaafarRammal** [comment]
Yes @jzzheng22 getters should only be used by custom agents otherwise they can be overridden

**Review by jzzheng22 — APPROVED** [review]
LGTM, thanks Jaafar

**Pull request merged**
