### PR TITLE
Rewrite Reshuffle() to remove infinite loop

### LINKED ISSUE #116: Deadlock in simulation for same config
Not sure if deadlock is the correct terminology here, but at the reshuffling stage, for 1 in 20 runs for the same config, the simulation lags forever. Below are the logs for two succeeding runs and two failing runs for the following config:

```
{
    "FoodOnPlatform": 100,
    "Team1Agents": 1,
    "Team2Agents": 1,
    "Team3Agents": 1,
    "Team4Agents": 1,
    "Team5Agents": 1,
    "Team6Agents": 1,
    "RandomAgents": 2,
    "AgentHP": 100,
    "AgentsPerFloor": 1,
    "TicksPerFloor": 10,
    "SimDays": 8,
    "ReshuffleDays": 1,
    "maxHP": 100,
    "weakLevel": 10,
    "width": 45,
    "tau": 10,
    "hpReqCToW": 2,
    "hpCritical": 5,
    "maxDayCritical": 3,
    "HPLossBase": 10,
    "HPLossSlope": 0.25
}
```

Succeeding logs:
[good.zip](https://github.com/SOMAS2021/SOMAS2021/files/7777766/good.zip)

Failing logs:
[bad.zip](https://github.com/SOMAS2021/SOMAS2021/files/7777768/bad.zip)

### PR DESCRIPTION
**Pull request by jzzheng22**
Closes #116.

Note that this function now allows agents to be shuffled onto their previous floors.

### CODE REVIEW

**Review by udai-arneja — APPROVED** [review]
LGTM, assuming you've tested it for edge casing etc. Otherwise I'll test it out in the morning and give a better review.

**Comment by jzzheng22** [comment]
> LGTM, assuming you've tested it for edge casing etc. Otherwise I'll test it out in the morning and give a better review.

I'll leave it until the morning to let you test it more

**Review by JaafarRammal — APPROVED** [review]
thanks

**Comment by udai-arneja** [comment]
> 

Done some more testing and it looks good to me, thanks X

**Pull request merged**
