### PR TITLE
Round() before int casting

### PR DESCRIPTION
**Pull request by mdubied**
# Summary

Perform math.Round() before to cast floats to integers in the health functions (updateHP, HPDecay, FoodRequired). This operation allows for better performance of the FoodRequired function

## Additional Information

The precision gained by this method was analysed by using the best set of health parameters we have so far, in a matlab script:
tau=15;
w=48;
b=5;
s=0.2;
WeakLevel=10;
HPCritical=3;
HPReqCToW=5;

### CODE REVIEW

**Comment by mdubied** [comment]
I am not too sure why the FoodRequired tests do not pass, as I did not implement them. Are they based on other health parameters?

**Comment by jzzheng22** [comment]
> I am not too sure why the FoodRequired tests do not pass, as I did not implement them. Are they based on other health parameters?

They're failing because the numbers in the tests assume you don't round. Can you fix the `want` value where they are now wrong please?

**Comment by mdubied** [comment]
So the want value is just the value that was manually computed?

**Comment by jzzheng22** [comment]
> So the want value is just the value that was manually computed?

Yes

**Comment by mdubied** [comment]
and which parameters are used? The ones in the config.json file produced by the frontend, or the ones in the config.json file that can be directly found in the first level of the repo?

**Comment by jzzheng22** [comment]
> and which parameters are used? The ones in the config.json file produced by the frontend, or the ones in the config.json file that can be directly found in the first level of the repo?

I used the ones that are in `health_test.go`.

**Review by jzzheng22 — APPROVED** [review]
Thanks Mathieu

**Pull request merged**
