### PR TITLE
Dashboard skeleton

### PR DESCRIPTION
**Pull request by JaafarRammal**
# Summary

Dashboard skeleton so others can develop in parallel. Built on top of BlueprintJS.

You can truthfully run it by building and running a docker instance locally (sorry we don't own much pipeline to build docker for each PR for now :) )

image

## Test
Need to add a CI for frontend, for now there is a `.prettierrc` file for formatting and you can run locally to test it

### CODE REVIEW

**Comment by udai-arneja** [comment]
Runs nicely, thanks really nice stuff XX

**Review by udai-arneja — APPROVED** [review]
Lovely

**Review by jzzheng22 — APPROVED** [review]
IDK typescript lol but sure

**Comment by JaafarRammal** [comment]
will add pipeline for the future see #168

**Pull request merged**
