### PR TITLE
Frontend improvements

### PR DESCRIPTION
**Pull request by JaafarRammal**

### CODE REVIEW

**Review by jzzheng22 — COMMENTED** [review]
Can I be annoying and ask for these changes too <3

1. Default to 'Use Food Per Agent' by default
2. Simulation Length default to 100 days?
3. Reshuffle period default of 7 days?
4. TimeOut longer (say 180? or even longer?)
5. Team1 and RandomAgent default values to 0 
6. Remove ability to change Agents Per Floor and Agents Max HP (and maybe even Initial HP)
7. The Treaties and Messages graphs have columns for agents which weren't in the tower - do we want that?
8. Can we replace the Config bit which shows agents per floor and show shuffle period?

**Comment by jzzheng22** [comment]
Thank you for your work <3

**Comment by jzzheng22** [comment]
Also I'm assuming you're already aware, but commenting this just in case - you can now open a log while the simulation is still running, but you can't open the 'Other Stats' section - that still causes a crash.

**Comment by JaafarRammal** [comment]
Other stats contains "messages" graphs which are only logged at the end of a Sim (it even crashes if there is a timeout). I'll try to resolve the timeout thing, and for the "sim is running" ill just disable the section until the sim finishes?

**Comment by JaafarRammal** [comment]
> 7- The Treaties and Messages graphs have columns for agents which weren't in the tower - do we want that?

@daryllimyt worked on the graphs, I think he's better suited into resolving this one if it's an issue!

**Comment by jzzheng22** [comment]
@JaafarRammal  btw Death log doesn't need to be disabled until sim finishes, that one is fine

**Comment by JaafarRammal** [comment]
Yep reenabled it

**Review by jzzheng22 — DISMISSED** [review]

**Comment by daryllimyt** [comment]
also thanks @JaafarRammal for consolidating the death stats :)

**Comment by daryllimyt** [comment]
I'm gonna do 7 in a different PR so you can get the other stuff in first

**Review by jzzheng22 — APPROVED** [review]

**Review by daryllimyt — APPROVED** [review]

**Pull request merged**
